spring:
  datasource:
    url: jdbc:h2:mem:test
    username: Peppe
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\\Users\\Giuse\\Desktop\\FileRepository
